### PR TITLE
Phil's changes to readme

### PR DESCRIPTION
**Pull request by ewels**

### CODE REVIEW

**Comment by ewels** [comment]
> **Additional information**
> Once an order has been submitted, additional information may be required from the user. For example, a sample information sheet may be requested by the facility. The facility should be able to specify a form for this, which should handle Excel and CSV files up- and download.

Does this mean that we do need to be able to have more than one template per facility?

**Comment by pekrau** [comment]
Good points all.

**Comment by pekrau** [comment]
@ewels Missed your point about the form for sample info: I don't really think that feature necessarily has much to do with the order template. Haven't really thought that far yet...

**Comment by ewels** [comment]
Yup - I guess as long as it references an order somehow, that can be done separately. Though if we write the system to handle an arbitrary number of forms then that might make things easier for people? I just thought it worth mentioning as it may affect whether we structure the database to handle multiple order templates or not.

**Pull request merged**
